Make traceback capture work with error already set (#175196)
I'm not yet satisfied with regression test, but checking if this helps.

This is the error from the added test without the fix:
```
$ python ../new_env/pytorch/test/test_autograd.py -k preserves_exc
E
======================================================================
ERROR: test_forward_traceback_preserves_exception_with_checkpoint (__main__.TestAutograd.test_forward_traceback_preserves_exception_with_checkpoint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 3364, in wrapper
    method(*args, **kwargs)
  File "/home/albandes/local/pytorch/3.12_release_binary/../new_env/pytorch/test/test_autograd.py", line 5985, in test_forward_traceback_preserves_exception_with_checkpoint
    y.sum().backward()
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_tensor.py", line 631, in backward
    torch.autograd.backward(
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/autograd/__init__.py", line 381, in backward
    _engine_run_backward(
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/autograd/graph.py", line 869, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/autograd/function.py", line 317, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_library/autograd.py", line 78, in backward
    result = info._backward_fn(ctx, *grads)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary/../new_env/pytorch/test/test_autograd.py", line 5967, in backward
    (x,) = ctx.saved_tensors
           ^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/utils/checkpoint.py", line 1173, in unpack_hook
    _run_fn_with_dynamo_disabled(frame.recompute_fn, *args)
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_compile.py", line 54, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1263, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/utils/checkpoint.py", line 1139, in _run_fn_with_dynamo_disabled
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/utils/checkpoint.py", line 1607, in recompute_fn
    fn(*args, **kwargs)
  File "/home/albandes/local/pytorch/3.12_release_binary/../new_env/pytorch/test/test_autograd.py", line 5977, in fn
    return torch.ops._test_autograd.sin_op(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_ops.py", line 1269, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/_library/autograd.py", line 110, in autograd_impl
    result = Generated.apply(*args, Metadata(keyset, keyword_only_args))  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.12_release_binary_env/lib/python3.12/site-packages/torch/autograd/function.py", line 596, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in method apply of FunctionMeta object at 0x37f73380> returned NULL without setting an exception

To execute this test, run the following from the base repo dir:
    python test/test_autograd.py TestAutograd.test_forward_traceback_preserves_exception_with_checkpoint

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 0.022s

FAILED (errors=1)
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/175196
Approved by: https://github.com/sraikund16